### PR TITLE
subscribe to topics

### PR DESCRIPTION
**Pull request by m1ga**
It's working but I'll clean up some code before

### CODE REVIEW

**Comment by m1ga** [comment]
example:

~~~javascript
// inside the register success event
gcm.subscribe({
            topic: "/topics/global",
            success: onSuccessTopic,
            error: onErrorTopic
});

// callback functions
function onSuccessTopic(e){
    console.log("success topic");
}
function onErrorTopic(e){
    console.log("error topic");
}
~~~

**Comment by m1ga** [comment]
added the same syntax for unsubscribe

**Comment by m1ga** [comment]
ready to merge

**Comment by morinel** [comment]
Thanks, why would you want to subscribe to a topic within the success handler of registerPush()?

Why not make it completely separate calls, like so:
```javascript
gcm.subscribe({
            senderId: "SENDER_ID",
            topic: "/topics/global",
            success: function(event) { ... },
            error: function(event { ... }
});
````
and
```javascript
gcm.unsubscribe({
            senderId: "SENDER_ID",
            topic: "/topics/global",
            success: function(event) { ... },
            error: function(event { ... }
});
```
Also please make any additional relevant properties available in the event callbacks.

**Comment by m1ga** [comment]
I've just put it in there because I wanted to be sure that it is registered to the push before subscribing to a channel. It can be used outside already. I've added the senderId to the function call and separated the getToken() function so you can even use that to just get the token.
Also I've added the topic to the callback again. Both functions (subscribe/unsub) return void so there isn't really much to add there

**Pull request merged**
