### PR TITLE
fixes crash when value evaluates to null, e.g. google_time is a long

### PR DESCRIPTION
**Pull request by dbankier**
~~~
07-29 08:45:40.476 25294 26684 D GCMIntentService: (IntentService[GCMIntentService--5]) [56788,57544] Push notification received
07-29 08:45:40.476 25294 26684 W Bundle  : Key google.sent_time expected String but value was a java.lang.Long.  The default value <null> was returned.
07-29 08:45:40.476 25294 26684 W Bundle  : Attempt to cast generated internal exception:
07-29 08:45:40.476 25294 26684 W Bundle  : java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
07-29 08:45:40.476 25294 26684 W Bundle  :      at android.os.BaseBundle.getString(BaseBundle.java:923)
07-29 08:45:40.476 25294 26684 W Bundle  :      at nl.vanvianen.android.gcm.GCMIntentService.onMessage(GCMIntentService.java:98)
07-29 08:45:40.476 25294 26684 W Bundle  :      at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:223)
07-29 08:45:40.476 25294 26684 W Bundle  :      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
07-29 08:45:40.476 25294 26684 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:102)
07-29 08:45:40.476 25294 26684 W Bundle  :      at android.os.Looper.loop(Looper.java:158)
07-29 08:45:40.476 25294 26684 W Bundle  :      at android.os.HandlerThread.run(HandlerThread.java:61)
07-29 08:45:40.476 25294 26684 D GCMIntentService: (IntentService[GCMIntentService--5]) [7,57551] Message key: "google.sent_time" value: "null"
07-29 08:45:40.476 25294 26684 W Bundle  : Key google.sent_time expected String but value was a java.lang.Long.  The default value <null> was returned.
07-29 08:45:40.486 25294 26684 W Bundle  : Attempt to cast generated internal exception:
07-29 08:45:40.486 25294 26684 W Bundle  : java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
07-29 08:45:40.486 25294 26684 W Bundle  :      at android.os.BaseBundle.getString(BaseBundle.java:923)
07-29 08:45:40.486 25294 26684 W Bundle  :      at nl.vanvianen.android.gcm.GCMIntentService.onMessage(GCMIntentService.java:106)
07-29 08:45:40.486 25294 26684 W Bundle  :      at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:223)
07-29 08:45:40.486 25294 26684 W Bundle  :      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
07-29 08:45:40.486 25294 26684 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:102)
07-29 08:45:40.486 25294 26684 W Bundle  :      at android.os.Looper.loop(Looper.java:158)
07-29 08:45:40.486 25294 26684 W Bundle  :      at android.os.HandlerThread.run(HandlerThread.java:61)
07-29 08:45:40.486 25294 26684 E TiApplication: (IntentService[GCMIntentService--5]) [2,57553] Sending event: exception on thread: IntentService[GCMIntentService--5] msg:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference; Titanium 5.3.0,2016/06/14 18:10,94fa8af
07-29 08:45:40.486 25294 26684 E TiApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
07-29 08:45:40.486 25294 26684 E TiApplication:         at nl.vanvianen.android.gcm.GCMIntentService.onMessage(GCMIntentService.java:108)
07-29 08:45:40.486 25294 26684 E TiApplication:         at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:223)
07-29 08:45:40.486 25294 26684 E TiApplication:         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
07-29 08:45:40.486 25294 26684 E TiApplication:         at android.os.Handler.dispatchMessage(Handler.java:102)
07-29 08:45:40.486 25294 26684 E TiApplication:         at android.os.Looper.loop(Looper.java:158)
07-29 08:45:40.486 25294 26684 E TiApplication:         at android.os.HandlerThread.run(HandlerThread.java:61)
07-29 08:45:40.506 25294 26684 E AndroidRuntime: FATAL EXCEPTION: IntentService[GCMIntentService--5]
~~~

### CODE REVIEW

**Comment by DFoxinator** [comment]
Thank you for this PR. This seems to be a major issue that just starting occurring. Do you happen to know how this happened? Did something in one of the Google APIs change?

Just curious, because a number of people just started experiencing this. https://github.com/morinel/gcmpush/issues/45

**Comment by dbankier** [comment]
Don't know. You could look through the git blame to see who/when that line of code was added. In any case, since google_time is Long it doesn't cast to String is ends up null.

**Comment by DFoxinator** [comment]
The weird thing is everything was working fine for months and I haven't updated the library in a long time. Same thing with the other people on that issue. That startsWith check was added in January.

**Comment by DFoxinator** [comment]
And looking at the crash reports for my app, it seems this error might have been occurring on a very small scale before, but just a couple of days ago, it started happening on nearly every push notification.

**Comment by morinel** [comment]
I fixed the issue in release 1.7

**Pull request closed without merging**
